# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  database: todos-api
  pool: 5
  timeout: 5000
  host: localhost
  username: <%= ENV["POSTGRES_USERNAME"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

test:
  adapter: postgresql
  database: todo-test
  pool: 5
  timeout: 5000
  host: localhost
  username: <%= ENV["POSTGRES_USERNAME"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

production:
  adapter: postgresql
  database: my_database_production
  pool: 5
  timeout: 5000